name: 'Hello World'
description: 'Greet someone and return 42'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
    default: '42'
runs:
  using: 'composite'
  steps: 
    - run: echo Hello ${{ inputs.who-to-greet }}, this is your first action!
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash